### ISSUE TITLE
Unable to find start of multi-part body.

### ISSUE THREAD

**Issue by andreespirela** [oakserver/oak#162]
[**Stacktrace**]
BadRequestError: Unable to find start of multi-part body.
    at readToStart (https://deno.land/x/oak@v5.1.0/multipart.ts:114:11)
    at async FormDataReader.read (https://deno.land/x/oak@v5.1.0/multipart.ts:283:5)
    at async Function.parseBody (file:///Users/andrespirela/mandarineorg/mandarinets/main-core/utils/httpUtils.ts:29:29)
    at async FactoryClass.methodArgumentResolver (file:///Users/andrespirela/mandarineorg/mandarinets/main-core/dependency-injection/diFactory.ts:130:35)
    at async requestResolver (file:///Users/andrespirela/mandarineorg/mandarinets/mvc-framework/core/internal/components/routing/routingResolver.ts:19:42)
    at async responseHandler (file:///Users/andrespirela/mandarineorg/mandarinets/mvc-framework/engine/mandarineMvcFrameworkStarter.ts:102:17)
    at async Application.#handleRequest (https://deno.land/x/oak@v5.1.0/application.ts:218:9)

[**Multipart**]
![image](https://user-images.githubusercontent.com/60560109/84425745-0f92c880-abf0-11ea-9d2e-93a9b6953411.png)

[**Code**]
```typescript
                let multipartBody = (await request.body()).value;
                console.log(await ((<FormDataReader> multipartBody)).read());
```

[**Additional**]
Content Type returned when `request.serverRequest.headers.get("content-type")`: `multipart/form-data; boundary=--------------------------329620794031183342837737`

In the picture, i'm selecting the second row which is empty. It's was a mistake taking the picture, the situation is happening in both scenarios with an empty field and without.

**Comment by andreespirela** [comment]
Ps: in the picture, i'm selecting the second row which is empty. It's was a mistake taking the picture, the situation is happening in both scenarios with an empty field and without.

**Comment by andreespirela** [comment]
Has the possible cause been found? @kitsonk

**Comment by kitsonk** [comment]
When there are actually no fields, the error is reproducible...  The body looks like this:

```
--------------------------329620794031183342837737--
```

Which is that the terminating string occurs before any part string occurs, which the logic didn't anticipate.
