### ISSUE TITLE
Error: Don't know how to parse column type: 1015

### ISSUE THREAD

**Issue by gungunfebrianza** [oakserver/oak#168]
Hello guys recently i am tried to fetch some row from my postgresql table,

```javascript
await this.pgClient.connect();
      const text = `SELECT * FROM public."hardwareConfig" WHERE hwid = $1`;
      const result = await this.pgClient.query({
        text,
        args: [hwid],
      });
      await this.pgClient.end();
```

there is nothing wrong with above code and the query, but seems we still cant parse any table that has an array column? since i have 3 column that contains **character varrying[] data type**.
here is the error

`Error: Don't know how to parse column type: 1015`

what do you think?

Stack Trace :
`Stack
"Error: Don't know how to parse column type: 1015

at decodeText (https://deno.land/x/postgres/decode.ts:233:13)    
at decode (https://deno.land/x/postgres/decode.ts:241:12)    
at QueryResult._parseDataRow (https://deno.land/x/postgres/query.ts:49:24)    
at QueryResult.handleDataRow (https://deno.land/x/postgres/query.ts:61:28)    
at Connection._preparedQuery (https://deno.land/x/postgres/connection.ts:513:18)    
at async Connection.query (https://deno.land/x/postgres/connection.ts:541:16)    
at async Client.query (https://deno.land/x/postgres/client.ts:24:12)    
at async HWIDClass.checkConfig (file:///C:/Users/Gun%20Gun%20Febrianza/Pictures/api-marketkoin2.0/model/hwid.ts:38:22)    
at async checkConfig (file:///C:/Users/Gun%20Gun%20Febrianza/Pictures/api-marketkoin2.0/controller/hwid.ts:17:32)    
at async Application.#handleRequest (https://deno.land/x/oak/application.ts:218:9)"`

**Comment by kitsonk** [comment]
This is not the postgres issue tracker.
