### ISSUE TITLE
Uncaught AddrInUse: when using --unstable --watch

### ISSUE THREAD

**Issue by MohammadHonarvar** [oakserver/oak#254]
I am on windows 10 and i tried running simple web server on deno latest:

```js
import { serve } from 'https://deno.land/std/http/server.ts';
const s = serve({ port: 8000 });
console.log('http://localhost:8000/');
for await (const req of s) {
  const file = await Deno.create('f.txt');
  await Deno.copy(req.body, file);
  req.respond({ body: 'Hello  asd asWorld\n' });
}
```

when I saved some changes, file watcher is restarting my app, and then error:

```
Watcher File change detected! Restarting!
error: Uncaught AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
    at Object.jsonOpSync (core.js:247:13)
    at opListen (deno:cli/rt/30_net.js:32:17)
    at Object.listen (deno:cli/rt/30_net.js:207:17)
    at Object.listen (deno:cli/rt/40_net_unstable.js:11:18)
    at serve (https://deno.land/std@0.73.0/http/server.ts:287:25)
    at <file:///C:/Users/Riz/Desktop/a/a.ts>:2:1
Watcher Process terminated! Restarting on file change...
```

**Comment by kitsonk** [comment]
You are not using oak in your example.
