### ISSUE TITLE
TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.

### ISSUE THREAD

**Issue by flemux** [oakserver/oak#262]
## Deno and Oak version
So, I upgraded my Deno version:
```
deno --version                                                       
deno 1.6.0 (release, x86_64-apple-darwin)
v8 8.8.278.2
typescript 4.1.2
```
I've using oak v4.0.0

## Error 

and now I've got the following errors when starting my application:
```
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Response,
  ~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/deps.ts:9:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Cookies,
  ~~~~~~~
    at https://deno.land/x/oak@v4.0.0/deps.ts:20:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Cookie,
  ~~~~~~
    at https://deno.land/x/oak@v4.0.0/deps.ts:21:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ApplicationOptions,
  ~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:5:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ListenOptions,
  ~~~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:6:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ListenOptionsBase,
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:7:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  ListenOptionsTls,
  ~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:8:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  State,
  ~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:9:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  CookiesGetOptions,
  ~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:14:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  CookiesSetDeleteOptions,
  ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:15:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { compose as composeMiddleware, Middleware } from "./middleware.ts";
                                       ~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:18:40

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Body,
  ~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:20:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  BodyOptions,
  ~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:21:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  BodyOptionsAsReader,
  ~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:22:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  BodyReader,
  ~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:23:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  BodyType,
  ~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:24:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  RouteParams,
  ~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:29:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Route,
  ~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:30:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  RouterContext,
  ~~~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:32:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  RouterMiddleware,
  ~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:33:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
export { HTTPMethods } from "./types.ts";
         ~~~~~~~~~~~
    at https://deno.land/x/oak@v4.0.0/mod.ts:36:10

Found 23 errors.
```

## Suggestions

If Oak only works up to a specific version of Deno, could we update the documentation to make this very clear for all using this library?  Looks at the latest PR tests are performed on `deno-version: v1.5.2` is this the version we should be using?

Alternatively, it looks like it is a simple case of using export **type** for the above errors, I could do this and raise a PR for both documentation and the type exports, let me know if you want me to do this.

## Additional Notes
As a side note, I tried using the following tsconfig.json:
```
{
  "compilerOptions": {
    "importsNotUsedAsValues": "remove",
    "isolatedModules": false
  }
}
```
But when I run the application I get the following message:
```
Unsupported compiler options in "/Users/frederiquelemieux/dev/Oppia/admin_app/backend/tsconfig.json".
  The following options were ignored:
    isolatedModules
```
I know this isn't an Oak issue, but if anyone can shed some light that would be much appreciated.

also these are not Oak errors but may be the result of an Oak dependency, so I'm unsure what to do, any suggestions welcome:
```
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

```

**Comment by flemux** [comment]
Okay, I've been digging into this a little more.

Using Deno version 1.5.x will work using the tsconfig given above.  So from what I understand version 1.6.0 no longer allows you to set   `"isolatedModules": false`.  Hence the message 
```
  The following options were ignored:
    isolatedModules
```
So I hope that helps if anyone gets that message.  

To summariuse, if you want to use Oak v4.0.0 with Deno v1.5.x you need to turn off isolatedModules in your tsconfig.

Now we still have the error messages from the std@library, I've used `deno info deps.ts` which confirms that the library is used by Oak. So any suggestions about how to resolve this?

![image](https://user-images.githubusercontent.com/67560754/101906322-ad238080-3bb0-11eb-95c4-f52e56a71fff.png)

**Comment by flemux** [comment]
Not using a version number helped resolve some issues with the import, but I'd like to fix the version used in my application.
this works:
export type { Middleware } from "https://deno.land/x/oak/mod.ts";

**Comment by kitsonk** [comment]
Oak v4 is not compatible with Deno 1.6 and won't be updated. Please use a more recent version like `https://deno.land/x/oak@v6.3.2/mod.ts`.
