### ISSUE TITLE
 server stops responding

### ISSUE THREAD

**Issue by hviana** [oakserver/oak#265]
I'm using Deno 1.6.0 witk Oak 6.4.0 and mongo@v0.13.0 in my project:
The server sometimes gives the following error:

```
TypeError: Invalid URL.
  at new URL (deno:op_crates/web/11_url.js:722:15)
  at Request.get url (request.ts:95:19)
  at dispatch (router.ts:841:45)
  at dispatch (middleware.ts:41:13)
  at server.ts:187:11
  at dispatch (middleware.ts:41:13)
  at composedMiddleware (middleware.ts:44:12)
  at Application.#handleRequest (application.ts:252:34)
  at Application.listen (application.ts:385:28)
  at async server.ts:210:3
```

When the error is thrown, sometimes the server stops responding, and the application keeps running, what can it be?
I'm using Oak in production and I need to resolve this urgent problem

**Comment by kitsonk** [comment]
I am not sure what the error is, likely some sort of invalid request, but oak should handle that failure point better.

**Comment by kitsonk** [comment]
Now when there is a valid URL, it is caught and the router middleware will reject it.  This should cause the rest of the application error handling to kick in.
