### ISSUE TITLE
TS2315 [ERROR]: Type 'Conn' is not generic

### ISSUE THREAD

**Issue by Pryla** [oakserver/oak#300]
Hi, this error comes on my macOs Big Sur machine with any oak-repo or even the hello world example. Any ideas?

```
$ deno run --allow-net server.ts 
Check file:///.../server.ts
error: TS2315 [ERROR]: Type 'Conn' is not generic.
export function isConn(value: unknown): value is Deno.Conn<Deno.NetAddr> {
                                                 ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/util.ts:66:50

TS2315 [ERROR]: Type 'Conn' is not generic.
  #conn?: Deno.Conn<Deno.NetAddr>;
          ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/http_server_native.ts:41:11

TS2315 [ERROR]: Type 'Conn' is not generic.
  constructor(requestEvent: RequestEvent, conn?: Deno.Conn<Deno.NetAddr>) {
                                                 ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/http_server_native.ts:49:50

TS2315 [ERROR]: Type 'Conn' is not generic.
        async function serve(conn: Deno.Conn<Deno.NetAddr>) {
                                   ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/http_server_native.ts:149:36

TS2315 [ERROR]: Type 'Conn' is not generic.
    conn?: Deno.Conn<Deno.NetAddr>,
           ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/application.ts:50:12

TS2315 [ERROR]: Type 'Conn' is not generic.
    secureOrConn: Deno.Conn<Deno.NetAddr> | boolean | undefined,
                  ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/application.ts:374:19

Found 6 errors.
```

Thanks!

**Comment by kitsonk** [comment]
What is your version of Deno?  v7 and later only supports Deno 1.9.0 and later.

**Comment by Pryla** [comment]
That's it. I am sorry I did not check this before - I was sure that everything was up to date.

Thank you!

**Comment by Cretezy** [comment]
Because of v1.9.1 reverting the type change for Deno.Conn, this seems to be broken again:

```
Check file:///home/charles/code/deno-test/server.ts
error: TS2315 [ERROR]: Type 'Conn' is not generic.
export function isConn(value: unknown): value is Deno.Conn<Deno.NetAddr> {
                                                 ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/util.ts:66:50

TS2315 [ERROR]: Type 'Conn' is not generic.
  #conn?: Deno.Conn<Deno.NetAddr>;
          ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/http_server_native.ts:41:11

TS2315 [ERROR]: Type 'Conn' is not generic.
  constructor(requestEvent: RequestEvent, conn?: Deno.Conn<Deno.NetAddr>) {
                                                 ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/http_server_native.ts:49:50

TS2315 [ERROR]: Type 'Conn' is not generic.
        async function serve(conn: Deno.Conn<Deno.NetAddr>) {
                                   ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/http_server_native.ts:149:36

TS2315 [ERROR]: Type 'Conn' is not generic.
    conn?: Deno.Conn<Deno.NetAddr>,
           ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/application.ts:50:12

TS2315 [ERROR]: Type 'Conn' is not generic.
    secureOrConn: Deno.Conn<Deno.NetAddr> | boolean | undefined,
                  ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/application.ts:374:19

Found 6 errors.
```

**Comment by kitsonk** [comment]
I have already fixed it in main and will tag a release in a few minutes.

**Comment by diadal** [comment]
this issue still on 1.10.2

**Comment by kitsonk** [comment]
No, you must be having some other issue.

**Comment by rbipin** [comment]
I'm having a similar issue with deno 1.12.2

>  deno --version
deno 1.12.2 (release, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.5

> deno run --allow-net server.ts
Check file:///Users/.../api/src/server.ts
error: TS2315 [ERROR]: Type 'Conn' is not generic.
  #conn?: Deno.Conn<Deno.NetAddr>;
          ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/http_server_native.ts:41:11

TS2315 [ERROR]: Type 'Conn' is not generic.
  constructor(requestEvent: RequestEvent, conn?: Deno.Conn<Deno.NetAddr>) {
                                                 ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/http_server_native.ts:49:50

TS2315 [ERROR]: Type 'Conn' is not generic.
        async function serve(conn: Deno.Conn<Deno.NetAddr>) {
                                   ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/http_server_native.ts:149:36

TS2315 [ERROR]: Type 'Conn' is not generic.
    conn?: Deno.Conn<Deno.NetAddr>,
           ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/application.ts:50:12

TS2315 [ERROR]: Type 'Conn' is not generic.
    secureOrConn: Deno.Conn<Deno.NetAddr> | boolean | undefined,
                  ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/application.ts:374:19

TS2345 [ERROR]: Argument of type 'unknown' is not assignable to parameter of type 'boolean | undefined'.
  Type 'unknown' is not assignable to type 'true'.
    const context = new Context(this, contextRequest, secure);
                                                      ~~~~~~
    at https://deno.land/x/oak@v7.2.0/application.ts:397:55

TS2315 [ERROR]: Type 'Conn' is not generic.
export function isConn(value: unknown): value is Deno.Conn<Deno.NetAddr> {
                                                 ~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v7.2.0/util.ts:66:50

Found 7 errors.

**Comment by kitsonk** [comment]
@rbipin you are using and outdated version of oak (v7.20) that is not compatible with the current version of Deno.
