### ISSUE TITLE
Native server hangs program after close if received at least one request

### ISSUE THREAD

**Issue by cmorten** [oakserver/oak#314]
```console
$ deno --version
deno 1.9.2 (release, x86_64-apple-darwin)
v8 9.1.269.5
typescript 4.2.2
```

Using `oak@v7.4.0` seeing behaviour whereby a deno program for running an oak server will hang / fail to exit despite an abort signal being fired ( which closes the server ) _if_ at least one request has been received by the server in it's lifetime.

Small repro:

```console
deno run -A --unstable repro.ts
```

```ts
// repro.ts

import {
  Application,
  Router,
  RouterContext,
} from "https://deno.land/x/oak@v7.4.0/mod.ts";

const router = new Router();
const app = new Application();

router.get("/", (ctx: RouterContext) => {
  ctx.response.body = "hello";
});

app.use(router.routes());
app.use(router.allowedMethods());

const controller = new AbortController();
const { signal } = controller;

app.addEventListener("listen", async ({ hostname, port, secure }) => {
  const protocol = secure ? "https" : "http";
  const url = `${protocol}://${hostname}:${port}`;

  console.log(url); // http://localhost:8000

  // Omitting the following two lines results in expected behaviour,
  // i.e. the server closes after the abort signal is fired and the
  // deno programe terminates.
  const response = await fetch(url);
  console.log(await response.text()); // hello

  console.log("Will abort in 1 second...");

  setTimeout(() => {
    console.log("aborting...");
    controller.abort();
    console.log("aborted!");
  }, 1000);
});

await app.listen(
  { hostname: "localhost", port: 8000, signal },
);

console.log("Server closed, yet the program is still running at this point? 🤔");
console.log("Does seem to eventually stop after a minute or so...");
```

What is observed in the above example is shortly after the abort signal is fired, the bottom two logs are executed ( as expected ) but then the deno program hangs for a minute or so with no output - we would expect the program to terminate immediately.

Running similar examples against [superoak](https://github.com/asos-craigmorten/superoak) for testing reveals that there is potentially an unhandled op / resource that is keeping the program running, specifically we see errors such as...

```console
AssertionError: Test case is leaking async ops.
Before:
  - dispatched: 0
  - completed: 0
After:
  - dispatched: 10
  - completed: 9

Make sure to await all promises returned from Deno APIs before
finishing test case.
    at assert (deno:runtime/js/06_util.js:33:13)
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:49:7)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:73:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:100:9)
    at async TestRunner.[Symbol.asyncIterator] (deno:runtime/js/40_testing.js:272:13)
    at async Object.runTests (deno:runtime/js/40_testing.js:347:22)
    at async file:///Users/craigmorten/git/asos-craigmorten/superoak/$deno$test.ts:5:1
```

and if we set `sanitizeOps: false` then...

```console
AssertionError: Test case is leaking resources.
Before: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr"
}
After: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr",
  "7": "httpConnection"
}

Make sure to close all open resource handles returned from Deno APIs before
finishing test case.
    at assert (deno:runtime/js/06_util.js:33:13)
    at resourceSanitizer (deno:runtime/js/40_testing.js:84:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:100:9)
    at async TestRunner.[Symbol.asyncIterator] (deno:runtime/js/40_testing.js:272:13)
    at async Object.runTests (deno:runtime/js/40_testing.js:347:22)
    at async file:///Users/craigmorten/git/asos-craigmorten/superoak/$deno$test.ts:5:1
```

where the latter error is perhaps more revealing ( the prior could be an issue with the test / test framework )?

We are also still seeing issues running Oak's `closeServer.ts` example - 

1. Run the `closeServer.ts` example
2. Hit `localhost:8000/close`
3. Observe that the `Finished.` line is printed, but the deno program has not terminted
4. Hit `localhost:8000/close` or `localhost:8000`
5. Observe that an uncaught promise rejection error regarding the stream controller is thrown from Oak's `http_server_native.ts` code

```console
$ deno run -A --unstable ./examples/closeServer.ts 
Start listening on 127.0.0.1:8000
  using HTTP server: native
GET / - 1ms
GET /close - 0ms
Finished.
error: Uncaught (in promise) TypeError: The stream controller cannot close or enqueue.
            controller.close();
                       ^
    at ReadableStreamDefaultController.close (deno:op_crates/fetch/11_streams.js:3465:15)
    at serve (file:///Users/craigmorten/git/oakserver/oak/http_server_native.ts:179:24)
```

**Comment by cmorten** [comment]
Suspect https://github.com/denoland/deno/issues/10508 may be related

**Comment by kitsonk** [comment]
I believe it is that upstream issue.

**Comment by kitsonk** [comment]
The upstream issue is fixed and part of Deno 1.11.

**Comment by cmorten** [comment]
Though the upstream issue has been resolved / merged, I am still encountering this issue with latest Oak on Deno `1.11.1`:

![Screenshot 2021-06-19 at 12 26 49](https://user-images.githubusercontent.com/11313985/122640886-b3fbf480-d0f9-11eb-8b26-35a67c6edc18.png)

Same steps to reproduce.

**Comment by pedraal** [comment]
I think that I experience the same problem in a simpler situation. I'm trying to implement a server restart logic to reload my router, as I was facing this issue, I tried a really simple implementation, here is my deno version, code and result :
```
deno --version
deno 1.12.2 (release, x86_64-apple-darwin)
v8 9.2.230.14
typescript 4.3.5
```

```
import { Application } from "https://deno.land/x/oak@v8.0.0/mod.ts";

let app = new Application();
const controller = new AbortController();
const { signal } = controller;
app.use((ctx) => {
  ctx.response.body = "test1";
});
const listenPromise = app.listen({ port: 8000, signal });

let text = await fetch("http://localhost:8000/");
console.log(await text.text());

controller.abort();
await listenPromise;

app = new Application();
app.use((ctx) => {
  ctx.response.body = "test2";
});
app.listen({ port: 8000 });

text = await fetch("http://localhost:8000/");
console.log(await text.text());
```

```
deno run -A --unstable repro.ts
test1
[uncaught oak error]: TypeError - The stream controller cannot close or enqueue.

    at ReadableStreamDefaultController.enqueue (deno:extensions/web/06_streams.js:3685:15)
    at serve (https://deno.land/x/oak@v8.0.0/http_server_native.ts:225:24)
error: Uncaught (in promise) TypeError: The stream controller cannot close or enqueue.
            controller.close();
                       ^
    at ReadableStreamDefaultController.close (deno:extensions/web/06_streams.js:3670:15)
    at serve (https://deno.land/x/oak@v8.0.0/http_server_native.ts:232:24)
```

I also tried several deno / oak versions combination, I didn't keep track of those test but the result was the very same.
I hope I'm not missing something silly 😓

**Comment by pedraal** [comment]
@cmorten thanks a lot, it's working like a charm with your fork 👍
