### ISSUE TITLE
Compile error in 7.4.0

### ISSUE THREAD

**Issue by kinegg** [oakserver/oak#316]
I just upgraded to 7.4.0 and now I get:

```
error: TS2376 [ERROR]: A 'super' call must be the first statement in 
the constructor when a class contains initialized properties, 
parameter properties, or private identifiers.
  constructor(
  ^
    at https://deno.land/x/oak@v7.4.0/range.ts:102:3
```

Typescript 4.2.4 (same error in 4.1.3)

**Comment by kitsonk** [comment]
What version of Deno are you using?

**Comment by kinegg** [comment]
Error is from Deno 1.8.1. I tried upgrading to 1.9.2 earlier, but then I got

```
error: TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
              return pd.url
                        ~~~
    at https://deno.land/std@0.74.0/permissions/mod.ts:17:25
```

**Comment by kinegg** [comment]
Maybe my `denon` is outdate, but trying to upgrade fails too. What a mess :)

```
deno install -qAf --unstable https://deno.land/x/denon/denon.ts
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
```

**Comment by kinegg** [comment]
@kitsonk but 1.9.2 doesn't compile either.

```
error: TS2339 [ERROR]: Property 'url' does not exist on type 'NetPermissionDescriptor'.
              return pd.url
                        ~~~
    at https://deno.land/std@0.74.0/permissions/mod.ts:17:25
```

Though I guess that's not related to Oak?

**Comment by kinegg** [comment]
@kitsonk you're right! https://deno.land/x/multiparser is using 0.89.

But I rely on multiparser so not sure what the solution is. Do you have any advice?
