### ISSUE TITLE
content-length does not match request.body size when using range requests

### ISSUE THREAD

**Issue by aperiosio** [oakserver/oak#352]
Hi *,

i think the 'content-length' is wrong when using HTTP/2 'Range', one byte is not counted.

```
$ deno --version
deno 1.11.0 (release, x86_64-apple-darwin)
v8 9.1.269.35
typescript 4.3.2
```

Tested with Oak : Release 7.7.0

Simple Test, load complete test.json file with 'Range 0-'
```
test({
  name: "range header from 0-",
  ignore: Deno.build.os === "windows",
  async fn() {
    const { context } = setup("/test.json");
    context.request.headers.set("Range", "bytes=0-");
    await send(context, context.request.url.pathname, { root: "./fixtures" });
    const response = await context.response.toDomResponse();
    assertEquals(response.status, 206);
    assertEquals(context.response.type, ".json");
    assertEquals(context.response.headers.get("content-length"), "23");
    assertEquals(await response.text(), `{\n  "hello": "world"\n}\n`);
  },
});
```

The test.json is :
`$ ls -l fixtures/test.json
-rw-r--r--  1 user  staff  23 Jun 28 22:03 fixtures/test.json`

`$ deno test --allow-net --allow-read send_test.ts`

Result :

```
range header from 0-
AssertionError: Values are not equal:

    [Diff] Actual / Expected

-   "22"
+   "23"

    at assertEquals (https://deno.land/std@0.99.0/testing/asserts.ts:234:9)
    at fn (file:///Users/stefanh/Data/Workspaces/oak/send_test.ts:500:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:21:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:58:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:85:9)
    at async runTest (deno:runtime/js/40_testing.js:199:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:244:7)
    at async file:///Users/stefanh/Data/Workspaces/oak/$deno$test.js:1:1
```

**Comment by stefnotch** [comment]
I think this can be closed now that it has been fixed?
