### ISSUE TITLE
Fails to get last byte when using range

### ISSUE THREAD

**Issue by stefnotch** [oakserver/oak#360]
When attempting to send a request with a `Range` header, where said range header points at the last byte of a file, a [416 status code](https://http.cat/416) is returned.

For example, when requesting the following file ( [index.ts](https://github.com/oakserver/oak/files/6771527/index.txt) ), this is what Deno returns. 

![image](https://user-images.githubusercontent.com/10220080/124638328-1dfef280-de8b-11eb-996c-4d0e46a503c5.png)
The content range of that file is `bytes 3050-3051/3052`

Then, when attempting to only get the final byte by setting the range field to `bytes=3051-`, Oak returns a failure status code

![image](https://user-images.githubusercontent.com/10220080/124638777-a9788380-de8b-11eb-9ba8-9d89943b2562.png)

I stumbled upon this seemingly pathological edge case while trying to play a video file served using oak. For some reason unknown to me, my browser (Firefox 89) decided to request the last byte of the video file. This appears to happen on quite a few video files, I'd guesstimate every 10th video file reproduces said behaviour.

**Comment by kitsonk** [comment]
What version of oak are you using?

**Comment by stefnotch** [comment]
I'm using `oak@v7.7.0`. I also tried patching it with [this fix](https://github.com/oakserver/oak/commit/4de406aaf221bbf6a856f99dc9d9cd10ed8de4b3), however, that didn't solve this issue.

To clarify, the script that I've started is [index.ts](https://github.com/oakserver/oak/files/6771527/index.txt). (Rename the `txt` extension to `ts`) Then, I've sent it a request like shown above using Insomnia.

**Comment by aperiosio** [comment]
Hmmm, wrote some tests, indeed, the range issue is not solved in complete yet.
```
//
test({
  name: "range header from 0-0, first byte",
  ignore: Deno.build.os === "windows",
  async fn() {
    const { context } = setup("/test.json");
    context.request.headers.set("Range", "bytes=0-0");
    await send(context, context.request.url.pathname, { root: "./fixtures" });
    const response = await context.response.toDomResponse();
    assertEquals(response.status, 206);
    assertEquals(context.response.type, ".json");
    assertEquals(context.response.headers.get("content-length"), "1");
    assertEquals(await response.text(), `{`);
  },
});


//
test({
  name: "range header from 22-22, the last byte",
  ignore: Deno.build.os === "windows",
  async fn() {
    const { context } = setup("/test.json");
    context.request.headers.set("Range", "bytes=22-22");
    await send(context, context.request.url.pathname, { root: "./fixtures" });
    const response = await context.response.toDomResponse();
    assertEquals(response.status, 206);
    assertEquals(context.response.type, ".json");
    assertEquals(context.response.headers.get("content-length"), "1");
    assertEquals(await response.text(), `\n`);
  },
});

//
test({
  name: "range header from 22-, last byte to end",
  ignore: Deno.build.os === "windows",
  async fn() {
    const { context } = setup("/test.json");
    context.request.headers.set("Range", "bytes=22-");
    await send(context, context.request.url.pathname, { root: "./fixtures" });
    const response = await context.response.toDomResponse();
    assertEquals(response.status, 206);
    assertEquals(context.response.type, ".json");
    assertEquals(context.response.headers.get("content-length"), "1");
    assertEquals(await response.text(), `\n`);
  },
});

test({
  name: "range header get the first byte and the last byte",
  ignore: Deno.build.os === "windows",
  async fn() {
    const { context } = setup("/test.json");
    context.request.headers.set("Range", "bytes=0-0,-1");
    await send(context, context.request.url.pathname, { root: "./fixtures" });
    const response = await context.response.toDomResponse();
    assertEquals(response.status, 206);
    assertEquals(context.response.type, ".json");
    assertEquals(context.response.headers.get("content-length"), "1");
    assertEquals(await response.text(), `{\n`);
  },
});

//
test({
  name: "range header from 10-10, 11th byte",
  ignore: Deno.build.os === "windows",
  async fn() {
    const { context } = setup("/test.json");
    context.request.headers.set("Range", "bytes=10-10");
    await send(context, context.request.url.pathname, { root: "./fixtures" });
    const response = await context.response.toDomResponse();
    assertEquals(response.status, 206);
    assertEquals(context.response.type, ".json");
    assertEquals(context.response.headers.get("content-length"), "1");
    assertEquals(await response.text(), `:`);
  },
});
```

results in : 

```



test range header ...bytes 0-5
 ok (6ms)
test range header from 0- ...bytes 0-22
 ok (3ms)
test range header from 0-0, first byte ... FAILED (3ms)
test range header from 22-22, the last byte ... FAILED (4ms)
test range header from 22-, last byte to end ... FAILED (2ms)
test range header get the first byte and the last byte ... FAILED (2ms)
test range header from 10-10, 11th byte ... FAILED (3ms)
test range header - multiple ranges ... ok (5ms)

failures:

range header from 0-0, first byte
RequestedRangeNotSatisfiableError: Requested Range Not Satisfiable
    at createHttpError (file:///Users/user/Workspaces/oak/httpError.ts:130:10)
    at parseRange (file:///Users/user/Workspaces/oak/range.ts:67:13)
    at sendRange (file:///Users/user/Workspaces/oak/send.ts:121:18)
    at send (file:///Users/user/Workspaces/oak/send.ts:313:11)
    at async fn (file:///Users/user/Workspaces/oak/send_test.ts:512:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:21:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:58:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:85:9)
    at async runTest (deno:runtime/js/40_testing.js:199:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:244:7)

range header from 22-22, the last byte
RequestedRangeNotSatisfiableError: Requested Range Not Satisfiable
    at createHttpError (file:///Users/user/Workspaces/oak/httpError.ts:130:10)
    at parseRange (file:///Users/user/Workspaces/oak/range.ts:67:13)
    at sendRange (file:///Users/user/Workspaces/oak/send.ts:121:18)
    at send (file:///Users/user/Workspaces/oak/send.ts:313:11)
    at async fn (file:///Users/user/Workspaces/oak/send_test.ts:529:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:21:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:58:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:85:9)
    at async runTest (deno:runtime/js/40_testing.js:199:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:244:7)

range header from 22-, last byte to end
RequestedRangeNotSatisfiableError: Requested Range Not Satisfiable
    at createHttpError (file:///Users/user/Workspaces/oak/httpError.ts:130:10)
    at parseRange (file:///Users/user/Workspaces/oak/range.ts:67:13)
    at sendRange (file:///Users/user/Workspaces/oak/send.ts:121:18)
    at send (file:///Users/user/Workspaces/oak/send.ts:313:11)
    at async fn (file:///Users/user/Workspaces/oak/send_test.ts:545:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:21:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:58:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:85:9)
    at async runTest (deno:runtime/js/40_testing.js:199:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:244:7)

range header get the first byte and the last byte
RequestedRangeNotSatisfiableError: Requested Range Not Satisfiable
    at createHttpError (file:///Users/user/Workspaces/oak/httpError.ts:130:10)
    at parseRange (file:///Users/user/Workspaces/oak/range.ts:47:13)
    at sendRange (file:///Users/user/Workspaces/oak/send.ts:121:18)
    at send (file:///Users/user/Workspaces/oak/send.ts:313:11)
    at async fn (file:///Users/user/Workspaces/oak/send_test.ts:560:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:21:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:58:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:85:9)
    at async runTest (deno:runtime/js/40_testing.js:199:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:244:7)

range header from 10-10, 11th byte
RequestedRangeNotSatisfiableError: Requested Range Not Satisfiable
    at createHttpError (file:///Users/user/Workspaces/oak/httpError.ts:130:10)
    at parseRange (file:///Users/user/Workspaces/oak/range.ts:67:13)
    at sendRange (file:///Users/user/Workspaces/oak/send.ts:121:18)
    at send (file:///Users/user/Workspaces/oak/send.ts:313:11)
    at async fn (file:///Users/user/Workspaces/oak/send_test.ts:576:5)
    at async asyncOpSanitizer (deno:runtime/js/40_testing.js:21:9)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:58:7)
    at async exitSanitizer (deno:runtime/js/40_testing.js:85:9)
    at async runTest (deno:runtime/js/40_testing.js:199:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:244:7)

failures:

	range header from 0-0, first byte
	range header from 22-22, the last byte
	range header from 22-, last byte to end
	range header get the first byte and the last byte
	range header from 10-10, 11th byte

test result: FAILED. 22 passed; 5 failed; 0 ignored; 0 measured; 0 filtered out (869ms)
```

**Comment by aperiosio** [comment]
@stefnotch possible quickfix to support positive ranges (as the tests in my comment above : `bytes=10-10` the 11th byte of a file, `bytes=22-` the last byte if the size of file is 23 byte,.. ): 

File range.ts : Line 66,67,68  change from
```
    if (start < 0 || start >= size || end < 0 || end >= size || start >= end) {
      throw createHttpError(Status.RequestedRangeNotSatisfiable);
    }
 ```
 to :
 ```
     if (start < 0 || start >= size || end < 0 || end >= size) {
      throw createHttpError(Status.RequestedRangeNotSatisfiable);
    }
 ```
 
 For support of negative ranges, i.e. `bytes=0-0,-1` i think there a a few more changes necessary.

**Comment by stefnotch** [comment]
Thank you for taking your time to investigate this. Oddly enough, with certain video files, I now get a content length mismatch error.

```
file.mp4:1 GET http://localhost:5000/file.mp4 net::ERR_CONTENT_LENGTH_MISMATCH 206 (Partial Content)
```

```
General:
  Request URL: http://localhost:5000/file.mp4
  Request Method: GET
  Status Code: 206 Partial Content
  Remote Address: 127.0.0.1:5000
  Referrer Policy: strict-origin-when-cross-origin

Response Headers:
  cache-control: max-age=0
  Content-Length: 1
  Content-Range: bytes 1239673092-1239673092/1239673093
  content-type: video/mp4
  date: Fri, 09 Jul 2021 16:48:06 GMT
  last-modified: Tue, 08 Jun 2021 14:52:04 GMT

Request Headers:
  Accept: */*
  Accept-Encoding: identity;q=1, *;q=0
  Accept-Language: en-GB,en;q=0.9
  Connection: keep-alive
  DNT: 1
  Host: localhost:5000
  If-Range: Tue, 08 Jun 2021 14:52:04 GMT
  Range: bytes=1239673092-1239673092
  Referer: http://localhost:5000/file.mp4
  sec-ch-ua: " Not;A Brand";v="99", "Microsoft Edge";v="91", "Chromium";v="91"
  sec-ch-ua-mobile: ?0
  Sec-Fetch-Dest: video
  Sec-Fetch-Mode: no-cors
  Sec-Fetch-Site: same-origin
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.64
```

**Comment by stefnotch** [comment]
> 
> 
> @stefnotch possible quickfix to support positive ranges (as the tests in my comment above : `bytes=10-10` the 11th byte of a file, `bytes=22-` the last byte if the size of file is 23 byte,.. ):
> 
> File range.ts : Line 66,67,68 change from
> 
> ```
>     if (start < 0 || start >= size || end < 0 || end >= size || start >= end) {
>       throw createHttpError(Status.RequestedRangeNotSatisfiable);
>     }
> ```
> 
> to :
> 
> ```
>     if (start < 0 || start >= size || end < 0 || end >= size) {
>      throw createHttpError(Status.RequestedRangeNotSatisfiable);
>    }
> ```
> 
> For support of negative ranges, i.e. `bytes=0-0,-1` i think there a a few more changes necessary.

I did some more testing and this fix does work. The error I'm getting afterwards seems to happen because Deno fails to read/send the one byte from the file.

**Comment by stefnotch** [comment]
To reproduce it
1. Download [index.ts](https://github.com/oakserver/oak/files/6771527/index.txt). (Rename the `txt` extension to `ts`)
2. Download https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4 
3. Start the script
4. Open Insomnia or a rest client of your choice
5. Make a `GET` request to wherever the file is. Make sure to set the range header to
```
Range      bytes=1128374-
```

Insomnia timeline
```
* Preparing request to http://localhost:5000/S/flower.mp4
* Current time is 2021-07-27T09:02:13.534Z
* Using libcurl/7.73.0-DEV OpenSSL/1.1.1g zlib/1.2.11 brotli/1.0.9 WinIDN libssh2/1.9.0_DEV nghttp2/1.41.0
* Using default HTTP version
* Disable timeout
* Enable automatic URL encoding
* Enable SSL validation
* Enable cookie sending with jar of 25 cookies
* Hostname localhost was found in DNS cache
*   Trying ::1:5000...
*   Trying 127.0.0.1:5000...
* Connected to localhost (127.0.0.1) port 5000 (#19)

> GET /S/flower.mp4 HTTP/1.1
> Host: localhost:5000
> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:89.0) Gecko/20100101 Firefox/89.0
> Range: bytes=1128374-
> Accept: */*

* Mark bundle as not supporting multiuse

< HTTP/1.1 206 Partial Content
< cache-control: max-age=0
< content-length: 1
< content-range: bytes 1128374-1128374/1128375
< content-type: video/mp4
< last-modified: Tue, 27 Jul 2021 09:01:58 GMT
< date: Tue, 27 Jul 2021 09:02:13 GMT


* Received 0 B chunk
* transfer closed with 1 bytes remaining to read
* Closing connection 19
```
Notice how it's expecting to read one more byte
