### ISSUE TITLE
Upgrading to native WebSocket fails

### ISSUE THREAD

**Issue by gcocatre** [oakserver/oak#370]
Running Deno 1.12.1, oak 8.0.0. The following code:

```
console.log(context.isUpgradable);
return context.upgrade();
```

produces the following output and error:

```
true
TypeError: Invalid Header: 'connection' header must be 'Upgrade'
    at Object.upgradeWebSocket (deno:extensions/http/01_http.js:325:13)
    at NativeRequest.upgrade (https://deno.land/x/oak@v8.0.0/http_server_native.ts:159:59)
    at Context.upgrade (https://deno.land/x/oak@v8.0.0/context.ts:198:51)
```

**Comment by kitsonk** [comment]
This is probably due to denoland/deno#11487 or denoland/deno#11494.

Is it reproducible with Deno 1.12.2?

What specifically did does the `connection` header look like?

**Comment by gcocatre** [comment]
With Deno 1.12.1, the problem seems to be the casing of the `connection` header indeed. Its value is `upgrade` (all lowercase);

With Deno 1.12.2, I now get this:

```
[uncaught oak error]: Http - no upgrade available

    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async Object.respondWith (deno:extensions/http/01_http.js:248:23)
    at async serve (https://deno.land/x/oak@v8.0.0/http_server_native.ts:226:13)
```

**Comment by kitsonk** [comment]
It feels like it is still a Deno issue.  The stack trace indicates that there is an attempt to upgrade the socket, but it doesn't believe it is upgradeable.

> What specifically did does the `connection` header look like?

**Comment by sullivansean27** [comment]
Hi, I happened to run into this issue while using oak v8.0.0 as well. I tested a few various deno versions and got the same `[uncaught oak error]: TypeError - Invalid Header: 'connection' header must be 'Upgrade'` error when using the same version, `Deno 1.12.1`. I thought I'd share what I ran into.

While investigating, I found [this stackoverflow post](https://stackoverflow.com/questions/50192812/firefox-combining-connection-keep-alive-upgrade-conflicts-with-mobile-operat) which pointed out that Firefox is unique in sending the upgrade header as `Connection: keep-alive, Upgrade`. When I tried testing on a chromium-based browser which sends `Connection: Upgrade` in the header, I no longer triggered @gcocatre's error. Perhaps the same thing is happening (I wouldn't know whether in Deno or Oak code) where the merged header is getting truncated?

**Comment by kitsonk** [comment]
The issue with a header like:

```
Connection: keep-alive, Upgrade
```

Was fixed after 1.12.2 and later (denoland/deno#11505).

That is why I am asking for what specifically the `connection` header looks like.  oak doesn't touch the header, so it is still very unlikely to be an oak issue.

**Comment by gcocatre** [comment]
> That is why I am asking for what specifically the `connection` header looks like. oak doesn't touch the header, so it is still very unlikely to be an oak issue.

The request connection header is the same in both cases:

```
console.log(context.isUpgradable);
console.log(context.request.headers.get("connection"));
```

outputs: 

```
true
upgrade
```

**Comment by kitsonk** [comment]
What other headers are there in the request?  oak uses the Deno std library at the moment to determine the value of `isAcceptable` but that then might not be valid when the built in socket is being upgraded.

**Comment by gcocatre** [comment]
Ok I can replicate the problem using my usual setup, which is an NGINX instance used as a reverse proxy over SSL in front of my Deno instance (which runs listens to plain HTTP):
```
Headers {
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
  "cache-control": "no-cache",
  connection: "upgrade",
  cookie: "jwt=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoic2Vzc2lvbiIsIm5hbWUiOiJHdWlsbGF1bWUiLCJ1dWlkIjo...",
  host: "localhost",
  origin: "https://localhost",
  pragma: "no-cache",
  "sec-websocket-extensions": "permessage-deflate; client_max_window_bits",
  "sec-websocket-key": "FUNmFgnOIoEmyVxZVYLuYQ==",
  "sec-websocket-version": "13",
  upgrade: "websocket",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4...",
  "x-real-ip": "127.0.0.1"
}
```

However when I access my deno instance directly (without going through NGINX) the connection seems to get upgraded to a WebSocket without errors:

```
Headers {
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "fr-FR,fr;q=0.9,en-US;q=0.8,en;q=0.7",
  "cache-control": "no-cache",
  connection: "Upgrade",
  cookie: "jwt=eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJ0eXBlIjoic2Vzc2lvbiIsIm5hbWUiOiJHdWlsbGF1bWUiLCJ1dWlkIjo...",
  host: "localhost:12345",
  origin: "http://localhost:12345",
  pragma: "no-cache",
  "sec-websocket-extensions": "permessage-deflate; client_max_window_bits",
  "sec-websocket-key": "BEHahU11Tw3rDVryQuci+w==",
  "sec-websocket-version": "13",
  upgrade: "websocket",
  "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4..."
}
```

The only difference that I can see, is that the contents of the "connection" header is transformed by NGINX to lowercase. But isn't the problem with Deno only accepting "Upgrade" (capitalized) supposed to be fixed in version 1.12.2?

**Comment by kitsonk** [comment]
The `sec-websocket-key` is being changed too. I suspect it is "invalid" based on what the native interface is expecting, but the error message isn't very informative.

**Comment by gcocatre** [comment]
The `sec-websocket-key` changes every time a new connection is made.

**Comment by kitsonk** [comment]
Correct. I don't think that is the issue. The current error is coming from the Rust side of Deno. The surfaced error message isn't very informative.

I will try to look into the Deno side a bit more in detail, but I am 99% sure it isn't oak.

**Comment by lucacasonato** [comment]
@gcocatre Could you try on Deno canary? `deno upgrade --canary`

**Comment by gcocatre** [comment]
@lucacasonato Same problem, with an additional one:

```
context.upgrade().then((socket) => console.log(socket));
```

`socket` is undefined with Deno 1.13.0 and canary.

**Comment by littledivy** [comment]
Can reproduce. `await ctx.upgrade()` is undefined in latest Deno canary.

**Comment by Schoude** [comment]
> Can reproduce. `await ctx.upgrade()` is undefined in latest Deno canary.

Same here. `await ctx.upgrade()` is undefined in the latest stable of deno `v1.13.2` and in the canary version yet `ctx.isUpgradable` is `true`.

**Comment by rotu** [comment]
FYI: when running without `--unstable`, the call to `ctx.upgrade()` fails more loudly:

```
[uncaught oak error]: TypeError - Upgrading web sockets not supported.
    at NativeRequest.upgrade (https://deno.land/x/oak@v9.0.0/http_server_native.ts:158:13)
    at Context.upgrade (https://deno.land/x/oak@v9.0.0/context.ts:198:51)
```

**Comment by rotu** [comment]
I think I found the cause of this issue.

`Deno.upgradeWebSocket` returns a property called `socket`, but `NativeRequest.upgrade` tries to unpack the `websocket` property.

https://github.com/denoland/deno/blob/ba8bbe6f1c11d4cf19ad0b916ba41cd919dbb042/ext/http/01_http.js#L398
https://github.com/oakserver/oak/blob/bcde4bee6b65cc7291694541839ec2dd5bf13a7b/http_server_native.ts#L160

**Comment by gcocatre** [comment]
@kitsonk sorry for coming back on this issue, but I still can't upgrade a WebSocket with Deno 1.14.1 and Oak 9.0.1 and NGINX in front of my app:

> [uncaught application error]: Http - no upgrade available

It's related to what I was saying on [August 14](https://github.com/oakserver/oak/issues/370#issuecomment-898755922) about NGINX transforming header names to lowercase, which apparently is [normal behavior for HTTP/2](https://stackoverflow.com/questions/64967098/how-to-get-nginx-to-add-a-header-without-converting-it-to-lowercase).

Upgrading to a WebSocket works fine when the `connection` header's value is `Upgrade` but not when it's `upgrade`.

I'm not sure who to turn to with this. I haven't been able to upgrade either Deno or Oak for 2 months now, it's frustrating…

**Comment by kitsonk** [comment]
Ok, I am still 99% sure it isn't oak.  There was the breaking change which made it worse, but now that has been fixed, it is clearly some other problem in Deno, which needs to be isolated.  I suspect if it was just stripped back to a Deno only implementation it would behave the same.
