### ISSUE TITLE
etag middleware does not work in deploy

### ISSUE THREAD

**Issue by KyleJune** [oakserver/oak#437]
My deployment wasn't serving any static files. The route I was going to uses the etag.factory(), then the matching route was just setting the body to "Hello world!". Locally it works fine and adds the etag but in deploy I got the following error.

```
Uncaught error TypeError: Right-hand side of 'instanceof' is not an object
    at getEntity (https://deno.land/x/oak@v10.0.0/etag.ts:33:14)
    at etag (https://deno.land/x/oak@v10.0.0/etag.ts:77:34)
```

**Comment by KyleJune** [comment]
Reproduction path:

```ts
import { Application, etag } from "https://deno.land/x/oak@v10.0.0/mod.ts";

const app = new Application();

app.use(etag.factory());

// Hello World!
app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

await app.listen({ port: 8000 });
```

https://dash.deno.com/playground/fresh-cow-68
