### ISSUE TITLE
Can't run Hello World example

### ISSUE THREAD

**Issue by felixsanz** [oakserver/oak#443]
Some people complain about this but i haven't found a solution on those issues:

```ts
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

await app.listen({ port: 8000 });
```

```
error: TS7053 [ERROR]: Element implicitly has an 'any' type because expression of type 'unique symbol' can't be used to index type 'ReadableStream<NativeRequest>'.
  Property '[SymbolConstructor.asyncIterator]' does not exist on type 'ReadableStream<NativeRequest>'.
    return stream[Symbol.asyncIterator]();
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.1.0/http_server_native.ts:281:12

TS2339 [ERROR]: Property 'entries' does not exist on type 'Headers'.
    for (const [key, value] of response.headers.entries()) {
                                                ~~~~~~~
    at https://deno.land/x/oak@v10.1.0/cookies.ts:297:49

TS2488 [ERROR]: Type 'Headers' must have a '[Symbol.iterator]()' method that returns an iterator.
      for (const [key, value] of headers) {
                                 ~~~~~~~
    at https://deno.land/x/oak@v10.1.0/server_sent_event.ts:243:34

TS2488 [ERROR]: Type 'Headers' must have a '[Symbol.iterator]()' method that returns an iterator.
    for (const [key, value] of responseHeaders) {
                               ~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.1.0/server_sent_event.ts:247:32

TS2339 [ERROR]: Property 'keys' does not exist on type 'Headers'.
    for (const key of [...context.response.headers.keys()]) {
                                                   ~~~~
    at https://deno.land/x/oak@v10.1.0/application.ts:312:52

TS2488 [ERROR]: Type 'URLSearchParams' must have a '[Symbol.iterator]()' method that returns an iterator.
  for (const [key, value] of ctx.request.url.searchParams) {
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.1.0/helpers.ts:43:30

TS2339 [ERROR]: Property 'entries' does not exist on type 'Headers'.
    return headers.entries();
                   ~~~~~~~
    at https://deno.land/x/oak@v10.1.0/middleware/proxy.ts:202:20

TS2488 [ERROR]: Type 'Headers' must have a '[Symbol.iterator]()' method that returns an iterator.
  for (const [key, value] of response.headers) {
                             ~~~~~~~~~~~~~~~~
    at https://deno.land/x/oak@v10.1.0/middleware/proxy.ts:228:30

Found 8 errors.
```

```
deno 1.16.4 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.4.2
```

**Comment by felixsanz** [comment]
Auto-answer: it needs no tsconfig or "deno.window" inside of compilerOptions.lib
