### ISSUE TITLE
Support mapping custom media types to extensions when reading form data.

### ISSUE THREAD

**Issue by aarongeorge** [oakserver/oak#458]
When trying to upload a `.wav` file as part of `form-data` in a `POST`, Oak errors out if the `content-type` for the `.wav` is `audio/vnd.wave`

Any ideas on how best to remedy this issue? I know I could change the content-type, but unfortunately I need to support it for my app.

Below is the very simple POST route handler

```typescript
import { Context } from '../../deps.ts'

// Upload
export const uploadFile = async (ctx: Context) => {
	try {
		const body = await ctx.request.body()

		if (body.type === 'form-data') {
			const formData = await body.value.read() // Errors here with: BadRequestError: Invalid media type for part: undefined
		}

		ctx.response.body = 'success'

	} catch (err) {
		console.log(err)
		ctx.response.body = { error: 'Something went wrong' }
		ctx.response.status = 500
	}
}
```

**Comment by aarongeorge** [comment]
I have created a pull request that resolves this issue here: https://github.com/oakserver/media_types/pull/12

**Comment by kitsonk** [comment]
I'm away from my computer at the moment, buy I believe there are ways to pass custom media types to be processed. I will take a look later.

**Comment by aarongeorge** [comment]
I have created a simpler version so it can be tested in isolation

```typescript
import { Application } from 'https://deno.land/x/oak/mod.ts'

const app = new Application()

app.use(async ctx => {
	try {
		const body = ctx.request.body()

		if (body.type === 'form-data') {
			const formData = await body.value.read()

			console.log(formData)
		}

		else {
			throw new Error('File uploads must be form-data')
		}

	} catch (err) {
		console.log(err)
		ctx.response.body = { error: err }
		ctx.response.status = 500
	}
});

await app.listen({ hostname: "localhost", port: 8000 })

```

Sending a request like this
```
POST / HTTP/1.1
Content-Type: multipart/form-data; charset=utf-8; boundary=__X_PAW_BOUNDARY__
Host: localhost:8000
Connection: close
User-Agent: Paw/3.3.4 (Macintosh; OS X/12.0.1) GCDHTTPRequest
Content-Length: 123163

--__X_PAW_BOUNDARY__
Content-Disposition: form-data; name="file"; filename="example.wav"
Content-Type: audio/vnd.wave

DATA REMOVED FROM HERE FOR BREVITY
--__X_PAW_BOUNDARY__--
```

Results in the following error being thrown:
```bash
BadRequestError: Invalid media type for part: undefined
    at getFile (https://deno.land/x/oak@v10.1.0/multipart.ts:131:13)
    at parts (https://deno.land/x/oak@v10.1.0/multipart.ts:172:30)
    at async FormDataReader.read (https://deno.land/x/oak@v10.1.0/multipart.ts:307:15)
```

**Comment by kitsonk** [comment]
You need to update to oak 10.2.0 but the following should now work:

```diff
		const body = ctx.request.body()

		if (body.type === 'form-data') {
---			const formData = await body.value.read()
+++			const formData = await body.value.read({ customContentTypes: { "audio/vnd.wave": "wav" }})

			console.log(formData)
		}
```

**Comment by aarongeorge** [comment]
Thank you very much, this has resolved the issues :)
