### ISSUE TITLE
Large file upload: out of range integral type conversion attempted

### ISSUE THREAD

**Issue by mdkq** [oakserver/oak#503]
When uploading a large file (2.62GB) I get this error:
`TypeError - out of range integral type conversion attempted`

Here is my controller
```js
async post(ctx) {
  const body = await ctx.request
    .body({ type: "form-data", limit: 0 })
    .value.read({
      maxFileSize: 21_474_836_480,
      outPath: `${Deno.cwd()}/static/fragment`,
    });
    
  // ...saving fields plus filepath to DB...

  ctx.response.status = 201;
}
```

Here's the stack trace
```
[uncaught application error]: TypeError - out of range integral type conversion attempted

request: { url: "http://localhost/api/fragment", method: "POST", hasBody: true }
response: { status: 404, type: undefined, hasBody: false, writable: true }

    at async ftruncate (deno:runtime/js/30_fs.js:258:5)
    at async parts (https://deno.land/x/oak@v10.5.1/multipart.ts:253:15)
    at async FormDataReader.read (https://deno.land/x/oak@v10.5.1/multipart.ts:415:15)
    at async post (file:///Users/marcus/Desktop/rose/server/controllers/fragment.js:22:18)
    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:41:7)
    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:41:7)
    at async restrict (file:///Users/marcus/Desktop/rose/server/middleware/auth.js:20:25)
    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:41:7)
    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:41:7)
    at async dispatch (https://deno.land/x/oak@v10.5.1/middleware.ts:41:7)
```

**Comment by kitsonk** [comment]
What is the output of `deno --version`?

**Comment by mdkq** [comment]
```
deno 1.19.3 (release, aarch64-apple-darwin)
v8 9.9.115.8
typescript 4.5.2
```

**Comment by kitsonk** [comment]
Fundamentally this is an issue with Deno, and the op infrastructure and out of range numbers being converted from JavaScript to Rust. It just happens to be oak calling the APIs in Deno.

What happens if you upgrade to 1.20.1 or later? There were some significant changes in that infrastructure recently.

**Comment by mdkq** [comment]
No change unfortunately. Thanks for looking into this
