### ISSUE TITLE
Empty body crashes server

### ISSUE THREAD

**Issue by shivam-tripathi** [oakserver/oak#508]
### Steps to reproduce:
1. Start the server
2. Hit the api:
```curl
curl  -H "Content-Type: application/json"  -X POST  localhost:3000/endpoint
```
Server crashes with: 
```
{
  body: Promise {
    <rejected> RangeError: Body exceeds a limit of 10485760.
    at Object.value (https://deno.land/x/oak@v10.1.0/body.ts:195:28)
    at HttpController.exec (file:///Users/shivamtripathi/code/apps/core/controllers/http_controller.ts:16:23)
    at dispatch (https://deno.land/x/oak@v10.1.0/middleware.ts:41:13)
    at https://deno.land/x/oak@v10.1.0/router.ts:1098:20
    at dispatch (https://deno.land/x/oak@v10.1.0/middleware.ts:41:13)
    at composedMiddleware (https://deno.land/x/oak@v10.1.0/middleware.ts:44:12)
    at dispatch (https://deno.land/x/oak@v10.1.0/router.ts:1104:28)
    at dispatch (https://deno.land/x/oak@v10.1.0/middleware.ts:41:13)
    at composedMiddleware (https://deno.land/x/oak@v10.1.0/middleware.ts:44:12)
    at Application.#handleRequest (https://deno.land/x/oak@v10.1.0/application.ts:344:34)
}
```

**Comment by kitsonk** [comment]
What does the server code look like?

**Comment by shivam-tripathi** [comment]
Error message was slightly confusing for me.

This fails for me:
```ts
// crashes
let value = body.value;
if (body.type === 'json') {
	value = await body.value;
}
```

All of these work:
```ts
// 1. Works
ctx.response.body = await ctx.request.body().value;
// 2. Works
const body = ctx.request.body();
// 3. Works
let value;
if (body.type === 'json') {
        value = await body.value;
} else {
	value = body.value;
}
```

I think this might be because of unhandled promise error. I overwrite the variable, so the other promise should ideally get out of scope - this was a little unexpected for me.

**Comment by Moroshima** [comment]
The same issue, it's so confusing.
