### ISSUE TITLE
[ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?

### ISSUE THREAD

**Issue by njfamirm** [oakserver/oak#514]
Hello
I ran into this problem after a while when I went back to my code
An update may have been made during this time...

```bash
$ deno --version
deno 1.17.3 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

```
$ y r
yarn run v1.22.17
$ npm-run-all run:*
$ deno run --allow-read --allow-net src/index.ts
Check file:///home/njfamirm/project/ts/Sunglasses/package/server/src/index.ts
error: TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
  async function getFile(contentType: string): Promise<[string, Deno.FsFile]> {
                                                                     ~~~~~~
    at https://deno.land/x/oak@v10.5.1/multipart.ts:186:70

TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
      let file: Deno.FsFile | undefined;
                     ~~~~~~
    at https://deno.land/x/oak@v10.5.1/multipart.ts:227:22

TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
function fstat(file: Deno.FsFile): Promise<Deno.FileInfo | undefined> {
                          ~~~~~~
    at https://deno.land/x/oak@v10.5.1/etag.ts:60:27

TS2551 [ERROR]: Property 'FsFile' does not exist on type 'typeof Deno'. Did you mean 'File'?
  if (body instanceof Deno.FsFile) {
                           ~~~~~~
    at https://deno.land/x/oak@v10.5.1/etag.ts:75:28

    'File' is declared here.
      export class File
                   ~~~~
        at asset:///lib.deno.ns.d.ts:1040:16

TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
): Promise<[Uint8Array | Deno.FsFile, Uint8Array | FileInfo]> {
                              ~~~~~~
    at https://deno.land/x/oak@v10.5.1/send.ts:124:31

TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
  let body: Uint8Array | Deno.FsFile;
                              ~~~~~~
    at https://deno.land/x/oak@v10.5.1/send.ts:125:31

TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
  body: Uint8Array | Deno.FsFile,
                          ~~~~~~
    at https://deno.land/x/oak@v10.5.1/send.ts:145:27

TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
  let body: Uint8Array | Deno.FsFile | null = null;
                              ~~~~~~
    at https://deno.land/x/oak@v10.5.1/send.ts:315:31

TS2724 [ERROR]: 'Deno' has no exported member named 'FsFile'. Did you mean 'File'?
  protected _file: Deno.FsFile | undefined;
                        ~~~~~~
    at https://deno.land/std@0.135.0/log/handlers.ts:99:25

Found 9 errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "run:deno" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
src/index.ts
```typescript
import {
  Application,
  Context,
  Router,
  send,
  Status,
} from "https://deno.land/x/oak/mod.ts";
import { info } from "https://deno.land/std/log/mod.ts";

import { checkFileExist } from "./util/checkFileExist.ts";

const router = new Router();
const app = new Application();

// serve home page
router.get("/", async (ctx: Context) => {
  ctx.response.status = 200;
  await send(ctx, "/", {
    root: `${Deno.cwd()}/../client/views`,
    index: "index.html",
  });
});

// serve 404 page
router.get("/(.*)", async (ctx: Context) => {
  ctx.response.status = 404;
  await send(ctx, "/", {
    root: `${Deno.cwd()}/../client/views`,
    index: "index.html",
  });
});

app.use(router.routes());
app.use(router.allowedMethods());

// page not found
app.use((context) => {
  context.response.status = Status.NotFound;
  context.response.body = `'${context.request.url}' not found`;
});

info("Serving on http://localhost:8000");
await app.listen({ port: 8000 });
```
src/util/checkFIleExist.ts
```typescript
import { Context } from "https://deno.land/x/oak/mod.ts";

// check file exist for serving static
export async function checkFileExist(ctx: Context) {
  const path = `${Deno.cwd()}/../client/${ctx.request.url.pathname}`;
  try {
    const fileInfo = await Deno.lstat(path);
    return fileInfo.isFile;
  } catch {
    console.log(path);
    return false;
  }
}
```

thanks!

**Comment by jiawei397** [comment]
Deno.File has been changed to Deno.FsFile, and Deno.File is deprecated when 1.20. Please update your deno version.
