### ISSUE TITLE
cannot read headers: request closed

### ISSUE THREAD

**Issue by jiawei397** [oakserver/oak#563]
When I just use autocannon to test performance, it is found that when the test ends, the service will crash.
```bash
autocannon -c 100 -d 5 -p 2 http://localhost:8000
```
The error message is :

```log
error: Uncaught (in promise) TypeError: cannot read headers: request closed
    return this.#request.headers;
                         ^
    at Object.get headerList (deno:ext/fetch/23_request.js:116:19)
    at Request.request.<computed> (deno:ext/fetch/23_request.js:581:62)
    at Request.get [headers] (deno:ext/fetch/23_request.js:252:48)
    at Request.get headers (deno:ext/fetch/23_request.js:465:18)
    at NativeRequest.get headers (https://deno.land/x/oak@v10.6.0/http_server_native_request.ts:68:26)
    at new Request (https://deno.land/x/oak@v10.6.0/request.ts:143:21)
    at new Context (https://deno.land/x/oak@v10.6.0/context.ts:142:20)
    at Application.#handleRequest (https://deno.land/x/oak@v10.6.0/application.ts:383:21)
    at Application.listen (https://deno.land/x/oak@v10.6.0/application.ts:559:28)
    at async file:///wk/deno/deno-oak/mod.ts:9:1
```

The Deno version:
```
deno 1.26.1 (release, aarch64-apple-darwin)
v8 10.7.193.3
typescript 4.8.3
```

The test code is:
```ts
import { Application } from "https://deno.land/x/oak/mod.ts";

const app = new Application();

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

await app.listen({ port: 8000 });
```

**Comment by kitsonk** [comment]
What happens when you upgrade to Deno 1.27?

**Comment by jiawei397** [comment]
What happened is still the same when I upgrade to 1.27.1.
```
deno 1.27.1 (release, aarch64-apple-darwin)
v8 10.8.168.4
typescript 4.8.3
```

**Comment by rossholdway** [comment]
Hi,

I'm also seeing this same issue - if the browser abruptly ends the request, it crashes the server with:

`deno run --allow-net --allow-env --allow-read --watch src/mod.ts`

```
error: Uncaught TypeError: cannot read headers: request closed
    return this.#request.headers;
                         ^
    at Object.get headerList (deno:ext/fetch/23_request.js:116:19)
    at Request.request.<computed> (deno:ext/fetch/23_request.js:581:62)
    at Request.get [headers] (deno:ext/fetch/23_request.js:252:48)
    at Request.get headers (deno:ext/fetch/23_request.js:465:18)
    at NativeRequest.get headers (https://deno.land/x/oak@v11.1.0/http_server_native_request.ts:68:26)
    at new Request (https://deno.land/x/oak@v11.1.0/request.ts:145:21)
    at new Context (https://deno.land/x/oak@v11.1.0/context.ts:173:20)
    at Application.#handleRequest (https://deno.land/x/oak@v11.1.0/application.ts:425:21)
    at Application.listen (https://deno.land/x/oak@v11.1.0/application.ts:610:28)
    ...
```

This is using Deno v1.28.2 and Oak 11.1.0.

**Comment by firecakes** [comment]
Can confirm, having the same issue. Is there any workaround for this until a proper fix is in place?

**Comment by dvv** [comment]
Deno 1.30.3, same thing

**Comment by rossholdway** [comment]
Yes, unfortunately I'm having to abandon Oak due to this. It's such a critical bug, a web framework that reliably crashes with high load is not something I can knowingly build a service on. It's a shame because the framework itself is great.

**Comment by dvv** [comment]
But seems it's cured with

**Comment by rossholdway** [comment]
@dvv Unfortunately your suggestion does not work for me. What does work is something like this (which prevents the server from crashing) within application.ts `#handleRequest`.

```typescript
 /** Processing registered middleware on each request. */
  async #handleRequest(
    request: ServerRequest,
    secure: boolean,
    state: RequestState,
  ): Promise<void> {

    // Handle missing headers due to early request closure
    try {
      request.headers;
    } catch(err) {
      console.warn(err);
      return;
    }

    const context = new Context(
    ...
```

However I don't think it's very elegant. It'd have been a little better if the catch above could call `#handleError` but that method expects `context` as an argument, but I believe`context` is part of the issue here! It'd be good to get some input from the maintainers, but the project seems to have been inactive for awhile now, hence why I'm having to move away :(

**Comment by dvv** [comment]
@rossholdway So you tried the listener and it still dumps when the load cancels?

I catch app errors as well:
```js
app.addEventListener("error", event => {
  if (event.error.name === "Http" && event.error.message === "connection closed before message completed") return
  appLogger.critical(`Unhandled exception: ${event.error.message}`, { ...event.context?.state.meta, stack: event.error.stack })
})
```

It's silent here in logs.

**Comment by rossholdway** [comment]
Hi @dvv. Yes, I did try your suggestion but unfortunately the server still crashed for me under heavy load.

**Comment by firecakes** [comment]
v10.5.1 seems to be the earliest version which does not have this issue and so that is what I'm now using.

**Comment by jiawei397** [comment]
> Hi @dvv. Yes, I did try your suggestion but unfortunately the server still crashed for me under heavy load.

The following method seems to work. Please try again.
```ts
addEventListener("unhandledrejection", (evt) => {
  evt.preventDefault();
  console.error(`unhandledrejection`, evt.reason);
});
```
This is my capture information:
```
unhandledrejection TypeError: cannot read headers: request closed
    at Object.get headerList (internal:ext/fetch/23_request.js:116:19)
    at Request.request.<computed> (internal:ext/fetch/23_request.js:620:43)
    at Request.get [headers] (internal:ext/fetch/23_request.js:267:48)
    at Request.get headers (internal:ext/fetch/23_request.js:482:18)
    at NativeRequest.get headers (https://deno.land/x/oak@v11.1.0/http_server_native_request.ts:68:26)
    at new Request (https://deno.land/x/oak@v11.1.0/request.ts:145:21)
    at new Context (https://deno.land/x/oak@v11.1.0/context.ts:173:20)
    at Application.#handleRequest (https://deno.land/x/oak@v11.1.0/application.ts:425:21)
    at Application.listen (https://deno.land/x/oak@v11.1.0/application.ts:610:28)
    at async file:///wk/deno/mod.ts:15:1
```
At least the service didn't crash.

**Comment by theLastOfCats** [comment]
looks like I got the same problem on [FrameworksBenchmarks](https://github.com/TechEmpower/FrameworkBenchmarks/pull/7955)

**Comment by kitsonk** [comment]
I tried re-creating with autocannon, but on modern versions of Deno, I can't seem to get it to throw like that. I suspect there have been changes in how Deno is handling `Request`s internally.

What I have done though is added handling around the construction of `Context` that if it throws while handling a request, that it results in the `Application` issuing an error event, instead of the exception being thrown in an unhandled way.  This should help clean up other related issues as well.
