### ISSUE TITLE
Transport endpoint is not connected

### ISSUE THREAD

**Issue by jiawei397** [oakserver/oak#564]
Recently, I encountered a difficult problem online. I don't know how to troubleshoot it. Please help me.

```
[uncaught application error]: NotConnected - Transport endpoint is not connected (os error 107)
   at async Listener.accept (deno:ext/net/01_net.js:147:44)
   at async accept (https://deno.land/x/oak@v11.1.0/http_server_native.ts:142:26)
```
This error happens every second, but I don't know how it is caused. I have two environments. One is for testing, and the other is for production. No errors were found in the test environment. Only the log platform of the production environment reported errors crazily.
It has not happened before, but suddenly started at a certain point in time.

I suspected that it was related to upgrading my Deno, but the problem log was not just upgraded, so it should be ruled out.

My service uses kafka, elastic search, redis, and mongoDB. It doesn't look like it's related to these databases.

The previous version of Deno is 1.26.1, and now it is 1.27.0. It is deployed in K8S container.

There is no clue now. Please give me some help. Thanks.

**Comment by jiawei397** [comment]
Well, the reason is found. It is a change of K8S TCP detection.It's not a pleasant experience
