### ISSUE TITLE
https support broken since oak@13

### ISSUE THREAD

**Issue by MarcLoupias** [oakserver/oak#636]
The https support is broken since `oak@13`.

The `example/httpsServer.ts` shows it.

Using the main branch, i have updated the example for `deno@1.40.x` :

```ts
/*
 * This is a basic example of a test server that listens on HTTPS and when using
 * the native HTTP server in Deno, will automatically server HTTP/2.
 *
 * This server uses self-signed encryption certificates, which also has a custom
 * root certificate authority. To use it as configured, you need to install and
 * trust the `tls/RootCA.crt` on your local system.
 */

// Importing some console colors
import {
  bold,
  cyan,
  green,
  yellow,
} from "https://deno.land/std@0.214.0/fmt/colors.ts";

import { Application } from "../mod.ts";

const app = new Application();

// Logger
app.use(async (ctx, next) => {
  await next();
  const rt = ctx.response.headers.get("X-Response-Time");
  console.log(
    `${green(ctx.request.method)} ${cyan(ctx.request.url.pathname)} - ${
      bold(
        String(rt),
      )
    }`,
  );
});

app.use(async (ctx, next) => {
  const start = Date.now();
  await next();
  const ms = Date.now() - start;
  ctx.response.headers.set("X-Response-Time", `${ms}ms`);
});

app.use((ctx) => {
  ctx.response.body = "Hello World!";
});

app.addEventListener("listen", ({ hostname, port, serverType }) => {
  console.log(
    bold("Start listening on ") + yellow(`${hostname}:${port}`),
  );
  console.log(bold("  using HTTP server: " + yellow(serverType)));
});

await app.listen({
  port: 8000,
  secure: true,
  cert: "./examples/tls/localhost.crt",
  key: "./examples/tls/localhost.key"
});
console.log(bold("Finished."));
```

Execution output is : 

```bash
Task example deno run --allow-net --allow-read examples/httpsServer.ts
error: Uncaught (in promise) InvalidData: No certificates found in cert file
        this.#httpServer = serve({
                           ^
    at listenTls (ext:deno_net/02_tls.js:142:36)
    at Object.serve (ext:deno_http/00_serve.js:589:16)
    at Object.start (file:///home/marco/dev/open-source/oak/http_server_native.ts:78:28)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:944:16)
    at startAlgorithm (ext:deno_web/06_streams.js:3662:14)
    at setUpReadableStreamDefaultController (ext:deno_web/06_streams.js:3626:23)
    at setUpReadableStreamDefaultControllerFromUnderlyingSource (ext:deno_web/06_streams.js:3692:3)
    at new ReadableStream (ext:deno_web/06_streams.js:5185:7)
    at Server.listen (file:///home/marco/dev/open-source/oak/http_server_native.ts:76:20)
    at Application.listen (file:///home/marco/dev/open-source/oak/application.ts:639:35)
marco@marco-ubuntu:~/dev/open-source/oak$ 
```

Without the [`ListenTlsOptions`](https://deno.land/api@v1.40.3?s=Deno.ListenTlsOptions) interface change we got this output :

```bash
error: Uncaught (in promise) TypeError: Unsupported 'certFile' / 'keyFile' options provided: use 'cert' / 'key' instead.
        this.#httpServer = serve({
                           ^
    at Object.serve (ext:deno_http/00_serve.js:569:11)
    at Object.start (file:///home/marco/dev/open-source/oak/http_server_native.ts:78:28)
    at Module.invokeCallbackFunction (ext:deno_webidl/00_webidl.js:944:16)
    at startAlgorithm (ext:deno_web/06_streams.js:3662:14)
    at setUpReadableStreamDefaultController (ext:deno_web/06_streams.js:3626:23)
    at setUpReadableStreamDefaultControllerFromUnderlyingSource (ext:deno_web/06_streams.js:3692:3)
    at new ReadableStream (ext:deno_web/06_streams.js:5185:7)
    at Server.listen (file:///home/marco/dev/open-source/oak/http_server_native.ts:76:20)
    at Application.listen (file:///home/marco/dev/open-source/oak/application.ts:639:35)
    at file:///home/marco/dev/open-source/oak/examples/httpsServer.ts:53:11
```

It seems with `oak@13` the `certFile` and `keyFile` props are more than deprecated ;-)

The `example/httpsServer.ts` with `oak@12.6.2` is working as expected with `deno@1.39.4` and `deno@1.40.x`.

**Comment by kitsonk** [comment]
I need to update the example, as the props changed in a breaking way because of the refactoring on a move from `Deno.serveHttp()` to `Deno.serve()`.  I refactored the changes in the example, but not actually the content.  `Deno.serve()` won't load from a file, but expects the value to be the content of any cert and key.  I need to double check the inline docs support that as well.

**Comment by MarcLoupias** [comment]
> expects the value to be the content of any cert and key

How could I have missed this...

It explains the Deno renaming from `certFile` to `cert` and `keyFile` to key.

Sorry and thanks for the explanation.

I think you can close this issue.
